theme = "base16_terminal"

[editor]
line-number = "relative"
mouse = false

[editor.lsp]
display-messages = true

[editor.search]
smart-case = true

[editor.cursor-shape]
insert = "underline"
normal = "block"
select = "bar"

[editor.file-picker]
hidden = false
