theme = "dark_plus"

[editor]
line-number = "relative"
mouse = false

[editor.lsp]
display-messages = true

[editor.search]
smart-case = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
